name: CI
on: [push, pull_request]
jobs:
  fmt:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 'stable'
          override: true
          components: rustfmt
      - run: cargo fmt --all -- --check